### ISSUE TITLE
Exclude field does't truly exclude manifest file from vet scan

### ISSUE THREAD

**Issue by hnanda21** [safedep/vet-action#122]
Hi Team, 

As the title suggests, upon setting the exclude field in vet action - with manifest file paths, some file(s) are stil scanned. Not sure if the config is missing something. Please refer to the image attached:

<img width="940" height="575" alt="Image" src="https://github.com/user-attachments/assets/eabd4697-38e1-4867-9dc3-0d56365f3300" />

Thank you.

**Comment by hnanda21** [comment]
Pardon for the duplicate, overlooked the comment. Thank you.

**Comment by abhisek** [comment]
This issue should be resolved. Can you please verify @hnanda21

**Comment by abhisek** [comment]
@hnanda21 The issue should be resolved. Please check once and verify.

**Comment by hnanda21** [comment]
Output indicates that the issue persists - the action picks up manifests that have been excluded using `exclude`
 field.

<img width="1041" height="591" alt="Image" src="https://github.com/user-attachments/assets/70e79eef-9edf-44e2-a031-b8568ff7b4f0" />

@abhisek

**Comment by abhisek** [comment]
@hnanda21 Interesting. I don't see the log line that you previously shared: `Running vet on ${file.filename} as ${lockfileName} for generating exceptions list`. Any idea why?

I will investigate this at my end as well.

**Comment by hnanda21** [comment]
<img width="1046" height="464" alt="Image" src="https://github.com/user-attachments/assets/10c00979-fa42-42fa-9bfd-3ce8d4db801a" />

You can check this @abhisek

**Comment by abhisek** [comment]
@hnanda21 The `exclude` actually take path patterns. Can you try any of:

```
test/api/pom.xml
test/api/*.xml
test/**/*.xml
```

I think there is some path mismatch with `./` character. Let me know if any of this works for your use-case.

**Comment by hnanda21** [comment]
<img width="1004" height="557" alt="Image" src="https://github.com/user-attachments/assets/efce6ec5-dee8-4001-a8fa-6dabf310069d" />

@abhisek output after removing the trailing `./`

**Comment by abhisek** [comment]
Thanks @hnanda21 

@Sahilb315 Can you do an analysis and check why the exclusion patterns are not working? I confirmed that they work in cli but somehow it is failing with GitHub Action

**Comment by abhisek** [comment]
@hnanda21 Just checking on this. Internal analysis found that vet will follow the exclusion config. But you will still see it in logs. Can you confirm if the pom.xml set as exclusion still fails the scan?

**Comment by hnanda21** [comment]
Current configuration for vet scan:
<img width="850" height="154" alt="Image" src="https://github.com/user-attachments/assets/0a7092ec-78d2-40c6-9748-0ed1e5e21b78" />

This fails the step when PR involves changes in `test/api/pom.xml` file (uses private package).

@abhisek @Sahilb315

**Comment by abhisek** [comment]
@Sahilb315 Can you try to reproduce this scenario at our end. I think @KunalSin9h tested this in the past. We have to setup a sample repository and try to reproduce this before we can debug and fix.

**Comment by KunalSin9h** [comment]
@abhisek why we are using `tempFile` (temporary) file for exception stage. ? any solid reason, since for vet scan with exceptions we are using original file name.

**Comment by KunalSin9h** [comment]
@abhisek this should fix: https://github.com/safedep/vet-action/pull/128

**Comment by abhisek** [comment]
Test case to confirm how vet matches path patterns: https://github.com/safedep/vet/pull/605

@KunalSin9h Let us go ahead with TS implementation of path pattern matching during pull request handling. We will consider "repository relative path patterns" as the input for the `exclude` config in `vet-action`.

**Comment by abhisek** [comment]
@hnanda21 This issue is fixed in the recent release. The `v1` tag is updated as well. Can you please verify if the issue is resolved at your end?

**Comment by goutham-madhawaraj** [comment]
Thank you for the fix and prioritising this issue Team ,  @abhisek @KunalSin9h .

**Comment by hnanda21** [comment]
Related to the fix deployed for this issue, the logs show this warning:
```
(node:1939) ExperimentalWarning: glob is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

To prevent any future breakdowns, we might want to consider a proper package 👍

**Comment by KunalSin9h** [comment]
@hnanda21 noted!
